### ISSUE TITLE
gyp binding

### ISSUE THREAD

**Issue by hitsthings** [pkrumins/node-jpeg#11]
Hi there!

I would have loved to use this module today, but I can't install it. I need gyp bindings. I know nothing about native Node, but I'll try to help if needed. 

Thanks!

**Comment by meteormatt** [comment]
Same with me.
Can not install on Mac.

```
~/workspace_test/socket.io-computer (master)$ cnpm install jpeg
npm WARN package.json queue3@1.0.2 No repository field.
npm WARN package.json socket.io-emitter@0.1.0 No repository field.
/
> jpeg@1.0.3 install /Users/Meteor/workspace_test/socket.io-computer/node_modules/jpeg
> node-gyp configure build

  CXX(target) Release/obj.target/jpeg/src/common.o
../src/common.cpp:10:17: error: calling a protected constructor of class
      'v8::HandleScope'
    HandleScope scope;
                ^
/Users/Meteor/.node-gyp/0.12.2/deps/v8/include/v8.h:816:13: note: declared
      protected here
  V8_INLINE HandleScope() {}
            ^
../src/common.cpp:11:37: error: no member named 'New' in 'v8::String'
    return Exception::Error(String::New(msg));
                            ~~~~~~~~^
../src/common.cpp:16:17: error: calling a protected constructor of class
      'v8::HandleScope'
    HandleScope scope;
                ^
/Users/Meteor/.node-gyp/0.12.2/deps/v8/include/v8.h:816:13: note: declared
      protected here
  V8_INLINE HandleScope() {}
            ^
../src/common.cpp:17:12: error: use of undeclared identifier 'ThrowException';
      did you mean 'ErrorException'?
    return ThrowException(ErrorException(msg));
           ^~~~~~~~~~~~~~
           ErrorException
../src/common.cpp:8:1: note: 'ErrorException' declared here
ErrorException(const char *msg)
^
../src/common.cpp:17:27: error: no viable conversion from 'Handle<v8::Value>' to
      'const char *'
    return ThrowException(ErrorException(msg));
                          ^~~~~~~~~~~~~~~~~~~
../src/common.cpp:8:28: note: passing argument to parameter 'msg' here
ErrorException(const char *msg)
                           ^
5 errors generated.
make: *** [Release/obj.target/jpeg/src/common.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/Meteor/.nvm/versions/node/v0.12.2/lib/node_modules/cnpm/node_modules/pangyp/lib/build.js:271:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Darwin 14.3.0
gyp ERR! command "node" "/Users/Meteor/.nvm/versions/node/v0.12.2/lib/node_modules/cnpm/node_modules/pangyp/bin/node-gyp.js" "configure" "build"
gyp ERR! cwd /Users/Meteor/workspace_test/socket.io-computer/node_modules/jpeg
gyp ERR! node -v v0.12.2
gyp ERR! pangyp -v v2.1.0
gyp ERR! not ok 
npm ERR! Darwin 14.3.0
npm ERR! argv "node" "/Users/Meteor/.nvm/versions/node/v0.12.2/lib/node_modules/cnpm/node_modules/.bin/npm" "--userconfig=/Users/Meteor/.cnpmrc" "--disturl=https://npm.taobao.org/mirrors/node" "--cache=/Users/Meteor/.cnpm" "--registry=https://registry.npm.taobao.org" "--node-gyp=/Users/Meteor/.nvm/versions/node/v0.12.2/lib/node_modules/cnpm/node_modules/pangyp/bin/node-gyp.js" "install" "jpeg"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.5
npm ERR! code ELIFECYCLE

npm ERR! jpeg@1.0.3 install: `node-gyp configure build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the jpeg@1.0.3 install script 'node-gyp configure build'.
npm ERR! This is most likely a problem with the jpeg package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp configure build
npm ERR! You can get their info via:
npm ERR!     npm owner ls jpeg
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/Meteor/workspace_test/socket.io-computer/npm-debug.log
```
